services:
  # frontend:
  #   container_name: frontend
  #   build: .
  #   ports:
  #     - ${FRONTEND_PORT}:${FRONTEND_PORT}
  #   restart: on-failure
  #   volumes:
  #     - ./:/app/
  #   depends_on:
  #     - echo_mysql
  #   env_file:
  #     - .env
  #   environment:
  #     - DB_CONNECTION=${DB_HOST}:${DB_PORT}
  #     - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
  #     - WAIT_BEFORE_HOSTS=15
  #     - WAIT_SLEEP_INTERVAL=3
  #     - FRONTEND_URL=http://${HOST}:${FRONTEND_PORT}
  #   networks:
  #     - go-web-network

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   restart: unless-stopped
  #   ports:
  #     - ${DB_PORT}:${DB_PORT}
  #   environment:
  #     - MYSQL_ROOT_HOST=${DB_HOST}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - go-web-network

  keydb:
    image: eqalpha/keydb
    container_name: keydb
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - go-web-network

  yugabytedb:
    image: yugabytedb/yugabyte:latest
    container_name: yugabyte01
    hostname: yugabyte01
    command: >
      bin/yugabyted start
      --base_dir=/home/yugabyte/yb_data
      --background=false
    ports:
      - "5433:5433"   # YSQL (PostgreSQL-compatible) port.
      - "9042:9042"   # YCQL (Cassandra-compatible) port.
      - "15433:15433" # YugabyteDB Admin UI port.
      - "7001:7000"   # YB-Master RPC port.
      - "9000:9000"   # YB-TServer RPC port.
    volumes:
      - yb_data:/home/yugabyte/yb_data
    networks:
      - go-web-network

volumes:
  mysql_data:
  yb_data:

networks:
  go-web-network:
    driver: bridge
