services:
  echo_app:
    container_name: echo_demo
    build: .
    ports:
      - ${EXPOSE_PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - echo_mysql
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_HOST}:${DB_PORT}
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
      - WAIT_BEFORE_HOSTS=15
      - WAIT_SLEEP_INTERVAL=3
      - FRONTEND_URL=http://localhost:3000
    networks:
      - echo-demo-stack

  echo_mysql:
    image: mysql:8.0
    container_name: echo_db
    ports:
      - ${EXPOSE_DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - echo-demo-stack

  echo_redis:
    image: redis
    container_name: ${REDIS_HOST}
    restart: unless-stopped
    ports:
      - ${REDIS_EXPOSE_PORT}:${REDIS_PORT}
    networks:
      - echo-demo-stack

  echo_yugabytedb:
    image: yugabytedb/yugabyte:latest
    container_name: echo_yugabytedb
    ports:
      - "5433:5433"  # YSQL port
      - "7000:7000"  # Master web UI
      - "9000:9000"  # TServer web UI
    environment:
      - YB_MASTER_ADDRS=yugabytedb:7100
    command: ["bin/yugabyted", "start", "--daemon=false", "--ui=false"]
    volumes:
      - yugabytedb_data:/mnt/master
      - yugabytedb_data:/mnt/tserver
    networks:
      - echo-demo-stack

volumes:
  database_mysql:
  yugabytedb_data:

networks:
  echo-demo-stack:
    driver: bridge

# docker-compose up echo_yugabytedb